backend:
  name: github
  repo: ellasoderberg/dinrytm

media_folder: static/img
public_folder: /img

collections:
  - name: "inlagg"
    label: "Inlägg"
    folder: "src/pages/lasmer"
    create: true
    slug: "{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publiceras", name: "date", widget: "date" }
      - { label: "Bild", name: "image", required: false, widget: "image"}
      - { label: 'Kategori', name: 'category', widget: 'select', options: ['aktuellt', 'forskning'] }
      - { label: "Text", name: "body", widget: "markdown" }

  - name: "tjanster"
    label: "Tjänster"
    folder: "src/pages/tjanster"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Bild", name: "image",  widget: "image"}
      - { label: "Sammanfattning", name: "ingress", required: false, widget: "text"}
      - { label: "Text", name: "body", widget: "markdown" }

  - name: "indextexts"
    label: "Texter startsida"
    folder: "src/pages"
    delete: false
    editor: 
      preview: false
    fields: 
      - { label: "Bild startsida", name: "image",  widget: "image"}
      - { label: "Slogan startsida", name: "Slogan", widget: "string"}
      - { label: "Box 1 titel", name: "box1title", widget: "string" }
      - { label: "Box 1 text", name: "box1text", widget: "text"}
      - { label: "Box 2 titel", name: "box2title", widget: "string" }
      - { label: "Box 2 text", name: "box2text", widget: "text"}
      - { label: "Box 3 titel", name: "box3title", widget: "string" }
      - { label: "Box 3 text", name: "box3text", widget: "text"}
      - { label: "Om startsida", name: "om", widget: "text" }


      