backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "inlagg"
    label: "Inlägg"
    folder: "src/pages/lasmer"
    create: true
    slug: "{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Template", name: "template", widget: "hidden", default: "article"}
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publiceras", name: "date", widget: "date" }
      - { label: "Bild", name: "image", required: false, widget: "image"}
      - { label: 'Kategori', name: 'category', widget: 'select', options: ['aktuellt', 'forskning'] }
      - { label: "Text", name: "body", widget: "markdown" }

  - name: "tjanster"
    label: "Tjänster"
    folder: "src/pages/tjanster"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Template", name: "template", widget: "hidden", default: "tjanst"}
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Ordning", name: "order",  widget: "number"}
      - { label: "Bild", name: "image",  widget: "image"}
      - { label: "Sammanfattning", name: "ingress", required: false, widget: "text"}
      - { label: "Text", name: "body", widget: "markdown" }

  - name: "start"
    label: "Texter startsida"
    editor: 
      preview: false
    files:
      - label: "Redigera texter startsida"
        name: "redigera"
        file: "src/pages/index.md"
        delete: false
        fields: 
          - { label: "Bild startsida", name: "image",  widget: "image"}
          - { label: "Slogan startsida", name: "slogan", widget: "string"}
          - { label: "Box 1 titel", name: "box1title", widget: "string" }
          - { label: "Box 1 text", name: "box1text", widget: "text"}
          - { label: "Box 1 leder till", name: "box1slug", widget: "string"}
          - { label: "Box 2 titel", name: "box2title", widget: "string" }
          - { label: "Box 2 text", name: "box2text", widget: "text"}
          - { label: "Box 2 leder till", name: "box2slug", widget: "string"}
          - { label: "Box 3 titel", name: "box3title", widget: "string" }
          - { label: "Box 3 text", name: "box3text", widget: "text"}
          - { label: "Box 3 leder till", name: "box3slug", widget: "string"}
          - { label: "Om startsida", name: "om", widget: "text" }

  - name: "om"
    label: "Om"
    editor: 
      preview: false
    files: 
      - label: "Redigera om"
        name: "redigera"
        file: "src/pages/om.md"
        delete: false
        fields: 
          - { label: "Template", name: "template", widget: "hidden", default: "om"}
          - { label: "Bild", name: "image",  widget: "image"}
          - { label: "Om Din rytm", name: "about", widget: "markdown" }
          - { label: "Om mig", name: "aboutme", widget: "markdown" }

  - name: "kontakt"
    label: "Kontakt"
    editor: 
      preview: false
    files: 
      - label: "Redigera kontakt"
        name: "redigera"
        file: "src/pages/kontakt.md"
        delete: false
        fields: 
          - { label: "Template", name: "template", widget: "hidden", default: "kontakt"}
          - { label: "Telefonnummer", name: "phone", widget: "string" }
          - { label: "E-post", name: "email", widget: "string" }

      