backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "inlagg"
    label: "Inlägg"
    folder: "src/pages/inlagg"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publiceras", name: "date", widget: "date" }
      - { label: "Bild", name: "image", required: false, widget: "image"}
      - { label: 'Kategori', name: 'category', widget: 'select', options: ['aktuellt', 'forskning'] }
      - { label: "Text", name: "body", widget: "markdown" }

  - name: "tjanster"
    label: "Tjänster"
    folder: "src/pages/tjanser"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Bild", name: "image",  widget: "image"}
      - { label: "Ingress", name: "ingress", widget: "text" }
      - { label: "Text", name: "body", widget: "markdown" }
      - label: "Priser"
        name: "price"
        widget: "object"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: 'Pris', name: 'number', widget: 'number' }
          - { label: "Beskrivning", name: "description", widget: "text" }

  - name: "indextexts"
    label: "Texter startsida"
    delete: false
    editor: 
      preview: false
    files:
      - label: "textbox1"
        name: "Textbox 1"
        file: "src/pages/index"
        fields:
          - { label: "Titel", name: "titlebox1", widget: "string" }
          - { label: "Text", name: "textbox1", widget: "text" }
      - label: "textbox2"
        name: "Textbox 2"
        file: "src/pages/index"
        fields:
          - { label: "Titel", name: "titlebox2", widget: "string" }
          - { label: "Text", name: "textbox2", widget: "text" }
      - label: "textbox3"
        name: "Textbox 3"
        file: "src/pages/index"
        fields:
          - { label: "Titel", name: "titlebox3", widget: "string" }
          - { label: "Text", name: "textbox3", widget: "text" }
      - label: "Om din rytm"
        name: "aboutindex"
        file: "src/pages/index"
        fields:
          - { label: "Text", name: "text", widget: "text"}

  - name: "ommig"
    label: "Om mig"
    delete: false
    files: 
      - label: "Om din rytm"
        name: "about"
        file: "src/pages/ommig"
        fields:
          - { label: "Text", name: "text", widget: "text"}
    


      